# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IHM.Probe')),
            ],
        ),
        migrations.AddField(
            model_name='probe',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IHM.Room'),
        ),
    ]
