# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
