# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHM', '0002_auto_20160710_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
