# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHM', '0003_probe_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_temp_aqua',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='max_temp_ext',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
