# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHM', '0004_auto_20160710_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe',
            name='is_aqua_probe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='probe',
            name='is_ext_probe',
            field=models.BooleanField(default=False),
        ),
    ]
